/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2018-08-31T18:04:36.544-04:00
  3.20.0.6

  Standalone prediction code with sample test data for GBMModel named gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://10.103.107.170:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://10.103.107.170:54321/3/Models.java/gbm-2760b04d-9dfd-436c-b780-7bdb2f372d85 > gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package com.aseigneurin.kafkah2o;

import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85", algorithm="gbm")
public class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85 extends GenModel {
    public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

    public boolean isSupervised() { return true; }
    public int nfeatures() { return 10; }
    public int nclasses() { return 1; }

    // Names of columns used by model.
    public static final String[] NAMES = NamesHolder_gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85.VALUES;

    // Column domains. The last array contains domain of response column.
    public static final String[][] DOMAINS = new String[][] {
            /* sqft */ null,
            /* lot_size_acres */ null,
            /* stories */ null,
            /* number_bedrooms */ null,
            /* number_bathrooms */ null,
            /* has_pool */ gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_5.VALUES,
            /* has_kitchen_island */ gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_6.VALUES,
            /* main_flooring_type */ gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_7.VALUES,
            /* has_granite_counters */ gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_8.VALUES,
            /* house_age_years */ null,
            /* selling_price */ null
    };
    // Prior class distribution
    public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
    // Class distribution used for model building
    public static final double[] MODEL_CLASS_DISTRIB = {1.0};

    public gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85() { super(NAMES,DOMAINS,"selling_price"); }
    public String getUUID() { return Long.toString(-6149842104570442688L); }

    // Pass in data in a double[], pre-aligned to the Model's requirements.
    // Jam predictions into the preds[] array; preds[0] is reserved for the
    // main prediction (class for classifiers or value for regression),
    // and remaining columns hold a probability distribution for classifiers.
    public final double[] score0( double[] data, double[] preds ) {
        java.util.Arrays.fill(preds,0);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_0.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_1.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_2.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_3.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_4.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_5.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_6.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_7.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_8.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_9.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_10.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_11.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_12.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_13.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_14.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_15.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_16.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_17.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_18.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_19.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_20.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_21.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_22.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_23.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_24.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_25.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_26.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_27.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_28.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_29.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_30.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_31.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_32.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_33.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_34.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_35.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_36.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_37.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_38.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_39.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_40.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_41.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_42.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_43.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_44.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_45.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_46.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_47.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_48.score0(data,preds);
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_49.score0(data,preds);
        preds[0] += 282311.76470588235;
        preds[0] = preds[0];
        return preds;
    }
}
// The class representing training column names
class NamesHolder_gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85 implements java.io.Serializable {
    public static final String[] VALUES = new String[10];
    static {
        NamesHolder_gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_0.fill(VALUES);
    }
    static final class NamesHolder_gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "sqft";
            sa[1] = "lot_size_acres";
            sa[2] = "stories";
            sa[3] = "number_bedrooms";
            sa[4] = "number_bathrooms";
            sa[5] = "has_pool";
            sa[6] = "has_kitchen_island";
            sa[7] = "main_flooring_type";
            sa[8] = "has_granite_counters";
            sa[9] = "house_age_years";
        }
    }
}
// The class representing column has_pool
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_5 implements java.io.Serializable {
    public static final String[] VALUES = new String[2];
    static {
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_5_0.fill(VALUES);
    }
    static final class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_5_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "no";
            sa[1] = "yes";
        }
    }
}
// The class representing column has_kitchen_island
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_6 implements java.io.Serializable {
    public static final String[] VALUES = new String[2];
    static {
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_6_0.fill(VALUES);
    }
    static final class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_6_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "no";
            sa[1] = "yes";
        }
    }
}
// The class representing column main_flooring_type
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_7 implements java.io.Serializable {
    public static final String[] VALUES = new String[3];
    static {
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_7_0.fill(VALUES);
    }
    static final class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_7_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "carpet";
            sa[1] = "hardwood";
            sa[2] = "tile";
        }
    }
}
// The class representing column has_granite_counters
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_8 implements java.io.Serializable {
    public static final String[] VALUES = new String[2];
    static {
        gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_8_0.fill(VALUES);
    }
    static final class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_ColInfo_8_0 implements java.io.Serializable {
        static final void fill(String[] sa) {
            sa[0] = "no";
            sa[1] = "yes";
        }
    }
}

class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_0 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_0_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_0_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -4091.1765f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        1258.8235f :
                        2150.4902f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_1 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_1_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_1_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -3682.0593f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        1132.9407f :
                        1935.4417f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_2 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_2_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_2_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -3313.853f :
                (data[0 /* sqft */] <2553.5f ?
                        919.8806f :
                        1709.9808f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_3 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_3_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_3_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -2982.4688f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        888.15466f :
                        1597.2375f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_4 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_4_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_4_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -2684.222f :
                (data[0 /* sqft */] <2553.5f ?
                        710.71375f :
                        1409.6487f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_5 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_5_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_5_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -2415.8f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        693.3203f :
                        1319.8448f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_6 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_6_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_6_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -2174.2188f :
                (data[0 /* sqft */] <2553.5f ?
                        545.2494f :
                        1163.55f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_7 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_7_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_7_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1956.7969f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        538.54846f :
                        1092.1146f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_8 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_8_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_8_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1761.1172f :
                (data[0 /* sqft */] <2553.5f ?
                        414.72562f :
                        961.7054f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_9 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_9_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_9_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1585.0062f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        415.8703f :
                        904.96356f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_10 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_10_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_10_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1426.5062f :
                (data[0 /* sqft */] <2553.5f ?
                        312.1025f :
                        795.99774f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_11 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_11_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_11_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1283.8562f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        318.8781f :
                        750.9969f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_12 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_12_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_12_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -704.00226f :
                791.9992f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_13 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_13_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_13_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -1085.0703f :
                (data[0 /* sqft */] <2553.5f ?
                        242.28062f :
                        601.98883f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_14 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_14_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_14_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -976.5625f :
                (data[3 /* number_bedrooms */] <3.5f ?
                        240.37656f :
                        573.42084f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_15 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_15_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_15_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -548.2153f :
                616.74023f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_16 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_16_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_16_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -824.08435f :
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        503.4177f :
                        183.31615f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_17 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_17_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_17_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -462.8717f :
                520.7293f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_18 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_18_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_18_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -695.38904f :
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        433.79166f :
                        145.69948f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_19 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_19_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_19_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -390.82846f :
                439.684f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_20 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_20_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_20_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -586.7672f :
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        374.12918f :
                        114.84635f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_21 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_21_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_21_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -330.01285f :
                371.26678f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_22 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_22_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_22_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -495.08905f :
                (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.47006837f ?
                        102.171425f :
                        352.04938f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_23 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_23_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_23_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -279.60052f :
                314.55157f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_24 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_24_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_24_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2295.5f ?
                -365.0836f :
                (Double.isNaN(data[0]) || data[0 /* sqft */] <2622.5f ?
                        321.87448f :
                        51.849377f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_25 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_25_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_25_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -235.03125f :
                264.40936f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_26 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_26_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_26_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[9]) || data[9 /* house_age_years */] <4.5f ?
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        490.74948f :
                        -183.44115f) :
                -368.77063f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_27 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_27_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_27_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -209.47969f :
                235.66406f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_28 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_28_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_28_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[9]) || data[9 /* house_age_years */] <4.5f ?
                (data[0 /* sqft */] <2437.5f ?
                        536.96375f :
                        -148.72366f) :
                -328.7506f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_29 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_29_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_29_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -198.13403f :
                222.9f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_30 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_30_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_30_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -71.54813f :
                        -264.12314f) :
                239.76361f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_31 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_31_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_31_class_0 {
    static final double score0(double[] data) {
        double pred =      (data[0 /* sqft */] <2240.0f ?
                -307.91876f :
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        247.32344f :
                        9.275521f));
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_32 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_32_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_32_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -55.81f :
                        -257.68124f) :
                223.92299f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_33 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_33_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_33_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -180.44844f :
                203.00468f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_34 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_34_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_34_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[9]) || data[9 /* house_age_years */] <4.5f ?
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        446.9961f :
                        -213.77083f) :
                -279.8697f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_35 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_35_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_35_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -47.809063f :
                        -269.15936f) :
                226.40715f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_36 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_36_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_36_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -168.25504f :
                189.28789f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_37 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_37_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_37_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -26.202812f :
                        -261.17188f) :
                205.26875f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_38 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_38_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_38_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -159.09792f :
                178.98555f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_39 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_39_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_39_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[9]) || data[9 /* house_age_years */] <4.5f ?
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        430.46616f :
                        -221.57448f) :
                -250.6725f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_40 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_40_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_40_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -23.475f :
                        -269.33688f) :
                209.14911f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_41 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_41_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_41_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -149.7882f :
                168.50937f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_42 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_42_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_42_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -6.15f :
                        -259.2525f) :
                189.57098f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_43 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_43_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_43_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -142.8934f :
                160.7539f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_44 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_44_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_44_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[9]) || data[9 /* house_age_years */] <4.5f ?
                (data[1 /* lot_size_acres */] <0.44501954f ?
                        413.50183f :
                        -225.66328f) :
                -225.40656f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_45 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_45_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_45_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -7.0384374f :
                        -265.19125f) :
                194.44911f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_46 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_46_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_46_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        -6.3353124f :
                        -238.6725f) :
                175.00491f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_47 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_47_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_47_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -143.02882f :
                160.9082f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_48 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_48_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_48_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[2]) || data[2 /* stories */] <1.5f ?
                -128.7257f :
                144.81758f);
        return pred;
    } // constant pool size = 6B, number of visited nodes = 1, static init size = 0B
}


class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Forest_49 {
    public static void score0(double[] fdata, double[] preds) {
        preds[0] += gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_49_class_0.score0(fdata);
    }
}
class gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85_Tree_49_class_0 {
    static final double score0(double[] data) {
        double pred =      (Double.isNaN(data[1]) || data[1 /* lot_size_acres */] <0.4699756f ?
                (data[2 /* stories */] <1.5f ?
                        21.473125f :
                        -245.37563f) :
                159.93124f);
        return pred;
    } // constant pool size = 10B, number of visited nodes = 2, static init size = 0B
}

